### ISSUE TITLE
好工具！可似乎不能用了。。

### ISSUE THREAD

**Issue by ringcrl** [AndreGeng/Alfred-VSC#1]
求更新~

**Comment by AndreGeng** [comment]
刚在电脑上试了下应该还可以用的,  要先装下vscode管理项目的插件(vscode-project-manager)[https://github.com/alefragnani/vscode-project-manager], 把当前的项目用这个插件保存下, 它会生成一个项目列表文件~/Library/Application Support/Code/User/projects.json, 然后就可以用这个alfred的workflow直接打开项目了.
